name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  showtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'ui/yarn.lock'
      - name: Install UI dependencies
        run: cd ui && yarn install
      - name: Build UI
        run: cd ui && yarn build
      - name: Build Go
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
